services:
  mcp_diec:
    image: frec_server
    build:
      context: ..
      dockerfile: ./docker/frec_server/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /app
    command: ["python", "mcp_servers/diec/diec.py"]
    networks:
      - frec_deploy_network
