services:
  mcp_google_translate:
    image: frec_server
    build:
      context: ..
      dockerfile: ./docker/frec_server/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /app
    command: ["python", "mcp_servers/google_translate.py"]
    networks:
      - frec_deploy_network