services:
  # Main system (front-end + back-end)
  frec_server:
    image: frec_server
    build:
      context: ..
      dockerfile: ./docker/frec_server/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /app
    environment:
      FREC_CONFIG_FILE: ${FREC_CONFIG_FILE:-frec-config.yml}
      FREC_DEPLOY_MODE: ${FREC_DEPLOY_MODE:-development}
    networks:
      - frec_deploy_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  frec_deploy_network:
