services:
  # Main system (front-end + back-end)
  frec_server:
    command: ["bash", "-c", "./prod.sh"]
    env_file: "frec-deploy.env"

  # Nginx (reverse proxy + HTTPS)
  nginx:
    image: jonasal/nginx-certbot:5.2.1
    env_file: "frec-deploy.env"
    init: true
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=hello@processtalks.com
      # - STAGING=1
      # - DEBUG=1
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - frec_server
    volumes:
      - ./secure:/secure # for http basic auth credentials. see setup-http-password.sh
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/user_conf.template.d
      - ./nginx/entrypoint.py:/entrypoint.py
      - nginx-letsencrypt:/etc/letsencrypt
    command: ["python3", "/entrypoint.py"]
    networks:
      - frec_deploy_network

volumes:
  nginx-letsencrypt:
    external: false